version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - dbdata:/var/opt/mssql
    healthcheck:
      test: >
        /opt/mssql-tools/bin/sqlcmd
        -S localhost -U sa -P "${SA_PASSWORD}"
        -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
