services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - dbdata:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_strong_Password1! -Q "SELECT 1"',
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

volumes:
  dbdata:
